#!/usr/bin/env node
// Generate src/test_vectors.rs from a real Sepolia LightClientFinalityUpdate
// (+ matching bootstrap sync committee). Run:
//
//   B=https://ethereum-sepolia-beacon-api.publicnode.com
//   curl -s "$B/eth/v1/beacon/light_client/finality_update" > /tmp/fu.json
//   R=$(curl -s "$B/eth/v1/beacon/headers/finalized" | jq -r .data.root)
//   curl -s "$B/eth/v1/beacon/light_client/bootstrap/$R" > /tmp/bootstrap.json
//   node scripts/gen_vector.mjs /tmp/fu.json /tmp/bootstrap.json \
//        d8ea171f3c94aea21ebc42a1ed61052acf3f9209c00e4efbaaddac09ed9b8078 90000075
//
// The committee/signature are emitted COMPRESSED (Ethereum wire form); the Rust
// test decompresses them with the `bls12_381` crate into the uncompressed form
// the Soroban host expects — exactly what an untrusted relayer would do.
import { readFileSync, writeFileSync } from "node:fs";

const [, , fuPath, bsPath, gvr, forkVersion] = process.argv;
const fu = JSON.parse(readFileSync(fuPath, "utf8")).data;
const bs = JSON.parse(readFileSync(bsPath, "utf8")).data;

const strip = (h) => h.replace(/^0x/, "");
const SPP = 8192n;
const period = (s) => BigInt(s) / SPP;

// Sanity: the bootstrap committee and the signature must be the same period.
if (period(fu.signature_slot) !== period(bs.header.beacon.slot)) {
  throw new Error(
    `period mismatch: sig ${period(fu.signature_slot)} vs bootstrap ${period(
      bs.header.beacon.slot
    )}`
  );
}

// uint256 decimal -> 32-byte little-endian hex (SSZ uint256 hash_tree_root form).
function u256le(dec) {
  let v = BigInt(dec);
  const out = Buffer.alloc(32);
  for (let i = 0; i < 32; i++) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out.toString("hex");
}

const committee = bs.current_sync_committee.pubkeys.map(strip).join("");
if (committee.length !== 512 * 48 * 2) throw new Error("committee size");

const att = fu.attested_header.beacon;
const fin = fu.finalized_header.beacon;
const exe = fu.finalized_header.execution;
const arr = (a) => "&[" + a.map((x) => `"${strip(x)}"`).join(", ") + "]";

const out = `//! AUTO-GENERATED by scripts/gen_vector.mjs from REAL Sepolia data.
//! Source: ethereum-sepolia-beacon-api.publicnode.com light_client/finality_update
//! + bootstrap. Fork: ${JSON.parse(readFileSync(fuPath, "utf8")).version}. Sync-committee period: ${period(
  fu.signature_slot
)}.
//! DO NOT EDIT BY HAND.
#![allow(dead_code)]

pub const GENESIS_VALIDATORS_ROOT: &str = "${strip(gvr)}";
pub const FORK_VERSION: &str = "${strip(forkVersion)}";
pub const SIGNATURE_SLOT: u64 = ${fu.signature_slot};

// --- attested header (the header the sync committee signed) ---
pub const ATT_SLOT: u64 = ${att.slot};
pub const ATT_PROPOSER: u64 = ${att.proposer_index};
pub const ATT_PARENT_ROOT: &str = "${strip(att.parent_root)}";
pub const ATT_STATE_ROOT: &str = "${strip(att.state_root)}";
pub const ATT_BODY_ROOT: &str = "${strip(att.body_root)}";

// --- finalized header ---
pub const FIN_SLOT: u64 = ${fin.slot};
pub const FIN_PROPOSER: u64 = ${fin.proposer_index};
pub const FIN_PARENT_ROOT: &str = "${strip(fin.parent_root)}";
pub const FIN_STATE_ROOT: &str = "${strip(fin.state_root)}";
pub const FIN_BODY_ROOT: &str = "${strip(fin.body_root)}";

pub const FINALITY_BRANCH: &[&str] = ${arr(fu.finality_branch)};

// --- finalized execution payload header ---
pub const EXE_PARENT_HASH: &str = "${strip(exe.parent_hash)}";
pub const EXE_FEE_RECIPIENT: &str = "${strip(exe.fee_recipient)}";
pub const EXE_STATE_ROOT: &str = "${strip(exe.state_root)}";
pub const EXE_RECEIPTS_ROOT: &str = "${strip(exe.receipts_root)}";
pub const EXE_LOGS_BLOOM: &str = "${strip(exe.logs_bloom)}";
pub const EXE_PREV_RANDAO: &str = "${strip(exe.prev_randao)}";
pub const EXE_BLOCK_NUMBER: u64 = ${exe.block_number};
pub const EXE_GAS_LIMIT: u64 = ${exe.gas_limit};
pub const EXE_GAS_USED: u64 = ${exe.gas_used};
pub const EXE_TIMESTAMP: u64 = ${exe.timestamp};
pub const EXE_EXTRA_DATA: &str = "${strip(exe.extra_data)}";
pub const EXE_BASE_FEE_LE: &str = "${u256le(exe.base_fee_per_gas)}";
pub const EXE_BLOCK_HASH: &str = "${strip(exe.block_hash)}";
pub const EXE_TX_ROOT: &str = "${strip(exe.transactions_root)}";
pub const EXE_WITHDRAWALS_ROOT: &str = "${strip(exe.withdrawals_root)}";
pub const EXE_BLOB_GAS_USED: u64 = ${exe.blob_gas_used};
pub const EXE_EXCESS_BLOB_GAS: u64 = ${exe.excess_blob_gas};

pub const EXECUTION_BRANCH: &[&str] = ${arr(fu.finalized_header.execution_branch)};

// --- sync aggregate ---
pub const SYNC_BITS: &str = "${strip(fu.sync_aggregate.sync_committee_bits)}";
pub const SIGNATURE_COMPRESSED: &str = "${strip(fu.sync_aggregate.sync_committee_signature)}";

// --- committee (512 compressed G1 pubkeys, concatenated) + aggregate ---
pub const AGGREGATE_PUBKEY_COMPRESSED: &str = "${strip(bs.current_sync_committee.aggregate_pubkey)}";
pub const COMMITTEE_COMPRESSED: &str = "${committee}";
`;

writeFileSync(new URL("../src/test_vectors.rs", import.meta.url), out);
console.log("wrote src/test_vectors.rs");
console.log("  fin exec block", exe.block_number, "state_root", exe.state_root);
console.log("  finality_branch len", fu.finality_branch.length);
console.log("  execution_branch len", fu.finalized_header.execution_branch.length);
