#!/usr/bin/env bash
# =============================================================================
# Deploy CLMM Contracts to Testnet
# =============================================================================
# This script deploys all CLMM contracts and configures the CLMM with verifiers.
#
# Requirements:
#   - source ./env.sh from the repo root
#   - stellar CLI installed
#   - cargo/rust toolchain installed with wasm32v1-none target support
#   - funded Stellar testnet identity
#   - CLMM circuit VK artifacts generated by circuits/noir/build_all.sh
#
# Usage:
#   chmod +x deploy-contracts.sh
#   ./deploy-contracts.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
CONTRACTS_DIR="${REPO_ROOT}/contracts"
ARTIFACTS_DIR="${REPO_ROOT}/circuits/artifacts"
VENDOR_DIR="${REPO_ROOT}/vendor/rs-soroban-ultrahonk"

NETWORK="${NETWORK:-testnet}"
SOURCE_ACCOUNT="${SOURCE_ACCOUNT:-wraith-clmm}"
ADMIN_KEY="${ADMIN_KEY:-}"
RUSTUP_TOOLCHAIN="${RUSTUP_TOOLCHAIN:-}"
STELLAR_RUSTUP_TOOLCHAIN="${STELLAR_RUSTUP_TOOLCHAIN:-1.92.0}"
STELLAR_BUILD="${STELLAR_BUILD:-0}"

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "Missing required command: $1"
        echo "Source env.sh and install the pinned toolchain from TOOLCHAIN.md."
        exit 1
    }
}

require_file() {
    [[ -f "$1" ]] || {
        echo "Missing required file: $1"
        exit 1
    }
}

run_cargo() {
    if [[ -n "$RUSTUP_TOOLCHAIN" ]]; then
        RUSTUP_TOOLCHAIN="$RUSTUP_TOOLCHAIN" cargo "$@"
    else
        cargo "$@"
    fi
}

run_stellar_build() {
    if [[ -n "$STELLAR_RUSTUP_TOOLCHAIN" ]]; then
        RUSTUP_TOOLCHAIN="$STELLAR_RUSTUP_TOOLCHAIN" stellar contract build
    else
        stellar contract build
    fi
}

require_cmd cargo
require_cmd git
require_cmd stellar

if [[ -z "$ADMIN_KEY" ]]; then
    ADMIN_KEY="$(stellar keys address "$SOURCE_ACCOUNT" 2>/dev/null || true)"
fi

if [[ -z "$ADMIN_KEY" ]]; then
    echo "ADMIN_KEY is not set and SOURCE_ACCOUNT '$SOURCE_ACCOUNT' was not found."
    echo "Set ADMIN_KEY=<G...> and SOURCE_ACCOUNT=<stellar identity> before deploying."
    exit 1
fi

for vk in clmm_mint clmm_burn clmm_swap_exact_in clmm_collect; do
    require_file "${ARTIFACTS_DIR}/${vk}/vk"
    bytes="$(wc -c < "${ARTIFACTS_DIR}/${vk}/vk" | tr -d ' ')"
    if [[ "$bytes" != "1760" ]]; then
        echo "Invalid VK size for ${vk}: ${bytes} bytes; expected 1760."
        echo "Regenerate with: ${REPO_ROOT}/circuits/noir/build_all.sh"
        exit 1
    fi
done

echo "========================================"
echo "Deploying Wraith CLMM Contracts"
echo "========================================"
echo "Network:        $NETWORK"
echo "Source account: $SOURCE_ACCOUNT"
echo "Admin:          $ADMIN_KEY"

# Step 1: Build WASMs
echo ""
echo "==> Building contracts..."
cd "$CONTRACTS_DIR"
if [[ "$STELLAR_BUILD" == "1" ]]; then
    run_stellar_build
else
    run_cargo build --target wasm32v1-none --release --package clmm --package merkle_tree
fi

if [[ ! -d "$VENDOR_DIR" ]]; then
    echo ""
    echo "==> Cloning rs-soroban-ultrahonk verifier..."
    mkdir -p "$(dirname "$VENDOR_DIR")"
    git clone https://github.com/NethermindEth/rs-soroban-ultrahonk "$VENDOR_DIR"
fi

echo ""
echo "==> Building UltraHonk verifier..."
cd "$VENDOR_DIR"
run_stellar_build
VERIFIER_WASM="${VENDOR_DIR}/target/wasm32v1-none/release/rs_soroban_ultrahonk.wasm"
require_file "$VERIFIER_WASM"

cd "$CONTRACTS_DIR"
CLMM_WASM="${CONTRACTS_DIR}/target/wasm32v1-none/release/clmm.wasm"
MERKLE_TREE_WASM="${CONTRACTS_DIR}/target/wasm32v1-none/release/merkle_tree.wasm"
require_file "$CLMM_WASM"
require_file "$MERKLE_TREE_WASM"

# Step 2: Deploy Merkle Tree
echo ""
echo "==> Deploying Merkle Tree..."
MERKLE_TREE=$(stellar contract deploy \
    --wasm "$MERKLE_TREE_WASM" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    -- --admin "$ADMIN_KEY" | tail -1)
echo "    MERKLE_TREE=$MERKLE_TREE"

# Step 3: Deploy Verifiers
echo ""
echo "==> Deploying Verifiers..."

echo "    Deploying Mint Verifier..."
MINT_VF=$(stellar contract deploy \
    --wasm "$VERIFIER_WASM" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    -- --vk_bytes-file-path "${ARTIFACTS_DIR}/clmm_mint/vk" | tail -1)

echo "    Deploying Burn Verifier..."
BURN_VF=$(stellar contract deploy \
    --wasm "$VERIFIER_WASM" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    -- --vk_bytes-file-path "${ARTIFACTS_DIR}/clmm_burn/vk" | tail -1)

echo "    Deploying Swap Verifier..."
SWAP_VF=$(stellar contract deploy \
    --wasm "$VERIFIER_WASM" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    -- --vk_bytes-file-path "${ARTIFACTS_DIR}/clmm_swap_exact_in/vk" | tail -1)

echo "    Deploying Collect Verifier..."
COLLECT_VF=$(stellar contract deploy \
    --wasm "$VERIFIER_WASM" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    -- --vk_bytes-file-path "${ARTIFACTS_DIR}/clmm_collect/vk" | tail -1)

echo "    Verifiers:"
echo "      MINT_VF=$MINT_VF"
echo "      BURN_VF=$BURN_VF"
echo "      SWAP_VF=$SWAP_VF"
echo "      COLLECT_VF=$COLLECT_VF"

# Step 4: Deploy CLMM
echo ""
echo "==> Deploying CLMM..."
CLMM=$(stellar contract deploy \
    --wasm "$CLMM_WASM" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    -- \
    --admin "$ADMIN_KEY" \
    --mint_vf "$MINT_VF" \
    --burn_vf "$BURN_VF" \
    --swap_vf "$SWAP_VF" \
    --collect_vf "$COLLECT_VF" \
    --merkle_tree "$MERKLE_TREE" | tail -1)

echo "    CLMM=$CLMM"

# Step 5: Configure authorized inserter
echo ""
echo "==> Configuring Merkle Tree authorized inserter..."
stellar contract invoke \
    --id "$MERKLE_TREE" \
    --source "$SOURCE_ACCOUNT" \
    --network "$NETWORK" \
    -- set_authorized_inserter \
    --admin "$ADMIN_KEY" \
    --inserter "$CLMM"

cat > "${REPO_ROOT}/deployments.clmm.${NETWORK}.json" <<JSON
{
  "network": "${NETWORK}",
  "sourceAccount": "${SOURCE_ACCOUNT}",
  "admin": "${ADMIN_KEY}",
  "contracts": {
    "clmm": "${CLMM}",
    "merkleTree": "${MERKLE_TREE}",
    "verifiers": {
      "mint": "${MINT_VF}",
      "burn": "${BURN_VF}",
      "swap": "${SWAP_VF}",
      "collect": "${COLLECT_VF}"
    }
  }
}
JSON

echo ""
echo "========================================"
echo "Deployment Complete!"
echo "========================================"
echo ""
echo "Contract Addresses:"
echo "  CLMM:       $CLMM"
echo "  MerkleTree: $MERKLE_TREE"
echo "  Mint VF:    $MINT_VF"
echo "  Burn VF:    $BURN_VF"
echo "  Swap VF:    $SWAP_VF"
echo "  Collect VF: $COLLECT_VF"
echo "  Manifest:   ${REPO_ROOT}/deployments.clmm.${NETWORK}.json"
echo ""
echo "Explorer Links:"
echo "  CLMM:       https://stellar.expert/explorer/testnet/contract/$CLMM"
echo "  MerkleTree: https://stellar.expert/explorer/testnet/contract/$MERKLE_TREE"
echo ""
