[package]
name = "clmm_swap_exact_in"
version = "0.1.0"
edition = "2024"
type = "bin"
description = "CLMM swap exact-in circuit - swap exact input for minimum output"

[dependencies]
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
wraith_lib = { path = "../wraith_lib" }
wraith_clmm_lib = { path = "../wraith_clmm_lib" }
